### ISSUE TITLE
Waiting for bazaar data

### ISSUE THREAD

**Issue by DrLen** [symt/BazaarNotifier#21]
When in the bazzar window, i cant see what is good and what is not to flip, mods i have is NEU SBA BN Patcher Optifine CTJS with dungeon utilitys and soopyaddons, i have put in the api key

**Comment by symt** [comment]
#22 

Fixed

**Comment by LAADrako** [comment]
![122111331111](https://user-images.githubusercontent.com/73834299/97873838-7425ff80-1d18-11eb-8838-14724d39f3b2.PNG)

Not fixed for me. I have the new version of the mod
